/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'johanwendt' at '2016-03-23 20:41' with Gradle 2.11
 *
 * @author johanwendt, @date 2016-03-23 20:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
